### ISSUE TITLE
Image export - support vector graphics such as eps and pdf

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1007]
Users have asked for export to pdfs  / eps formats and to produce higher resolution pngs.

There is potentially a 'hack' for this to insert a bitmap into a pdf, but to approach this properly, i.e. convert to vector, is not trivial. Investigation required.

Layers:

- [ ] AST grid, text labels, title, etc
- [ ] region and annotation (Konva)
- [ ] beam element (Konva)
- [ ] colorbar (Konva)
- [ ] background as transparent, white, and black
- [ ] catalog overlay (WebGL2)
- [ ] contours (WebGL2)
- [ ] vector field (WebGL2)
- [ ] raster (WebGL2)

**Comment by kswang1029** [comment]
> suggested by Chin-Fei:
support eps, svg image format
full/compressed resolution
rgb
possible tool: imageMagick
