### ISSUE TITLE
Publication quality image output

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-frontend#1009]
This epic includes the following features:

- [ ] export image plot as vector graphics such as eps and pdf
- [x] export image plot as high resolution (600dpi?) png format
- [x] colorbar in the image viewer
- [x] configurable overlays such as labels, ticks, title etc
- [ ] ability to control the aspect ratio of an image plot programmatically (now it is bundled with the widget size and can be  configured only via mouse)
- [ ] ability to add annotations on the image such as text, marker (eg +), arrow, rectangle, ellipse etc
- [ ] add annotation from a text file 
- [ ] scriptable

Note that the image export should also support the multi-panel and channel view (once they are implemented)

Requirement [doc](https://docs.google.com/document/d/1eeaLg5kUctiYkwBCcemx6BXrFajrwLozc_9m1WGx4yk/edit#heading=h.ef2zpcraea3n)

previous note
> Image export to pdf / eps / higher resolution png.
The 'hack' would be to insert a bitmap into a pdf for the time being. But to address this properly requires conversion from raster to vector which is not trivial.
We need to define what we mean by publication quality,

**Comment by Kechil** [comment]
Padding:  suggest adding an option to increase the padding (background space) around the raster image, so that things like text labels of coordinate tick marks does not get cut off in the exported image.
