### ISSUE TITLE
Frontend performance profiling and optimisation

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#1634]
There are a number of troubling issues with the frontend's performance. In no particular order, the following issues need to be investigated (e.g. proper performance profiling to determine bottlenecks and potential for improvement) and hopefully optimised:

- [ ] 1. Firefox and safari performance is pretty poor. I have no idea why (other than the higher event rate on safari)
- [ ] 2. The AST overlay rendering needs to be optimised, especially when in multi-panel view.
- [ ] 3. Simply viewing and image and moving your mouse over an image (even after closing the spatial profilers) can use a fair amount of CPU (up to 20% of one core for me).
- [x] 4.1 Regions are implemented using react-konva, and don't scale well. Tools like PyBDSF can result in hundreds, or even thousands of regions. Users often want to import these files and the frontend just completely freezes up. Fixed in https://github.com/CARTAvis/carta-frontend/pull/1664
- [x] 4.2 virtualize region list in region list widget  https://github.com/CARTAvis/carta-frontend/issues/1694
- [ ] 5. RasterViewComponent/ContourViewComponent/CatalogViewGLComponent are 3 major heavy components in the image viewer, and we can obviously feel the latency when these 3 components are enabled, but even there are no contour/catalog data at all, so can we improve the UX when there is no contour/catalog data?

(@duidae to lead investigation and optimisation, @veggiesaurus to assist)

**Comment by duidae** [comment]
did some investigations and:
* about (2), @veggiesaurus do you mean the temporary freeze of the AST layer when cursor behaviors (ex: scrolling to zoom) switched from one image panel to another?

* about (4): this is a relatively concrete symptom and possible solutions I can imagine now are:
 1. at least showing progress bar when importing regions to have better UX during the freeze time(tried importing 1000 regions and the duration could be ~30sec)
 2. try splitting regions into multiple konva layers to avoid re-rendering the whole thing
 3. disable listen when current field of view contains too many regions (ex: > 50 regions)
 4. dont render regions outside FOV
 5. konva cache(havent sort out how to yet)
 6. when checking the performance with profiler, it seems that some of the overhead are from react's operations, and since React-konva is more about rendering things on canvas using the advantage of JSX, probably it is doable to strip off react (i.e. use konva directly to draw things) to avoid those overhead? But may need some effort to rewrite konva related stuffs
 
@veggiesaurus do you think the ideas above make sense?

**Comment by veggiesaurus** [comment]
> * about (2), @veggiesaurus do you mean the temporary freeze of the AST layer when cursor behaviors (ex: scrolling to zoom) switched from one image panel to another?

Are you suggesting that we only update the active image's AST layer when scrolling or panning? DS9 does something similar: when you pan, it doesn't update. When you scroll, it seems to update, but you can definitly feel a bit of latency.

https://user-images.githubusercontent.com/592504/141763540-8b8e1c9e-e8cb-4811-ada2-b3f670d7d956.mp4

**Comment by kswang1029** [comment]
Need to re-review the performance and update the tasks if needed.
