### ISSUE TITLE
Full Stokes support

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#211]
For Stokes cubes and polarization studies: 
- [ ] The Stokes channels contained in a cube need to be determined by WCS
- [x] Users need to be able to display multiple spectral profile widgets for the same region
- [x] Users need to be able to display spectral profiles for the current Stokes, or explicitly selecting I, Q, U or V when browsing a cube with any currently selected Stokes value
- [ ] Users need to be able to display multiple Stokes values on the same profiler graph
- [ ] Users need to be able to display polarisation intensity and polarisation angle in a spectral profiler
- [ ] A scatter plot widget showing Qz vs Uz for all channels (with color determined by channel)
- [ ] A template layout needs to be developed for Stokes IQU and IQUV cubes (showing profiles and scatter plot by default

**Comment by veggiesaurus** [comment]
@arusstaylor Users should be able to display Stokes profiles for cursor and regions in 1.1

![stokes_cursor](https://user-images.githubusercontent.com/592504/55162647-eb74d400-5170-11e9-9cf5-3685084d9740.gif)

![stokes_regions](https://user-images.githubusercontent.com/592504/55162654-f0398800-5170-11e9-96cb-16b2b4630fae.gif)

Next step is making this _efficient_
