### ISSUE TITLE
enhancement of spectral profile widget for v1.3

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#643]
- [x] conversion of spectral axis (x), such as velocity frame, frequency, velocity, optical/radio definition, etc.(c.f. casaviewer)
- [ ] unit conversion of intensity axis (y), such as Jy/beam <-> K, MJy/sr, Jy/arcsec^2, etc. (c.f. casaviewer)
- [x] ability to view multiple profiles in one widget
- [x] custom displayed x and y range (with text input) **DONE**

**Comment by veggiesaurus** [comment]
I think it makes more sense to have each check point as separate issues, and use this issue as an epic to contain all spectral profile enhancements for 1.3. We may assign different sub-issues to different people
