### ISSUE TITLE
enhancement of spectral profile widget for v1.4

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-frontend#644]
- [ ] profile fitting (Gaussian, Lorentzian, Voigt etc)
- [x] overplotting labels of molecular transitions by querying molecular database
- [x] channel smoothing (hanning, boxcar, binning)
