### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-frontend#872]
- [x] Upgrade to typescript 3.7
- [ ] Make use of [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining) where appropriate.
- [x] Introduce the singleton pattern for some stores and services (`AppStore`, `BackendService`, `ScriptingService`, ...)

**Comment by veggiesaurus** [comment]
Another big change that we should make: use stricter Typescript rules (no implicit `any`, strict `null` checks)
